# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Forma55pro(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(539, 304)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(260, 110, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(370, 110, 111, 31))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 180, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(380, 180, 41, 31))
        self.textEdit_2.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 250, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.textEdit_3 = QtWidgets.QTextEdit(Form)
        self.textEdit_3.setGeometry(QtCore.QRect(370, 250, 71, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(180, 30, 161, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 110, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 180, 93, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.textEdit_4 = QtWidgets.QTextEdit(Form)
        self.textEdit_4.setGeometry(QtCore.QRect(150, 180, 51, 31))
        self.textEdit_4.setObjectName("textEdit_4")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.button_clickrecord)
        self.pushButton_2.clicked.connect(Form.button_clicklisten)
        self.pushButton_3.clicked.connect(Form.button_clickshow)
        self.pushButton_4.clicked.connect(Form.button_choose)
        self.pushButton_5.clicked.connect(Form.button_recg)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "录音"))
        self.pushButton_2.setText(_translate("Form", "听声"))
        self.pushButton_3.setText(_translate("Form", "识别"))
        self.label.setText(_translate("Form", "孤立字识别"))
        self.pushButton_4.setText(_translate("Form", "选择"))
        self.pushButton_5.setText(_translate("Form", "识别"))
